### ISSUE TITLE
Used labels are not cleared at getter/setter border

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-validator-js#17]
Failing case:

```js
a:+{get a(){a:return 0}}
```

**Comment by ikarienator** [comment]
Wowow... That seems to be a difference between ES5 and browser implementation.

**Comment by ikarienator** [comment]
Should we add this spec incompatibility to our library or not?

**Comment by michaelficarra** [comment]
Let's go with the standard here. We align with implementations when

0. they all agree
0. they conflict with the spec
0. a large number of users make use of the difference

**Comment by ikarienator** [comment]
Nice answer.

**Comment by michaelficarra** [comment]
Can you point to the section of the spec that allows this? I am only aware of duplicate labels being allowed across function declaration boundaries.
