### ISSUE TITLE
Can "const" VariableDeclaration show up in for-loops?

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-validator-js#21]
This is not checked but does if const is in for loop, it does not parse.

**Comment by emattson** [comment]
Do you have a specific code example? If it's not in the spec I'm not sure we should check it.

**Comment by ikarienator** [comment]
I think in es6 spec it is not allowed.

**Comment by michaelficarra** [comment]
It is allowed, and it makes sense. See [section 13.6.4.10](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-bindinginstantiation).
