### ISSUE TITLE
Publish a new npm package

### ISSUE THREAD

**Issue by couchand** [shapesecurity/shift-validator-js#30]
The current version on npm seems to be wildly out of date.  This caused me many headaches trying to debug mysterious issues, only to discover that this is the one shift package that relies on shift-reducer v1.0.3.  Please push a new version.

**Comment by bakkot** [comment]
Sorry, yes, I hadn't realized I forgot to npm publish. This will be done soon.

**Comment by couchand** [comment]
Thanks! :beers:

**Comment by bakkot** [comment]
[Done](https://github.com/shapesecurity/shift-validator-js/tree/v2.0.0).
